name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [11, 17]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
    - name: Run
      run: ./gradlew run
    - name: Test
      run: ./gradlew test
      continue-on-error: true
